---
title: "å†°é›¶å®éªŒå®¤ | CryoZero Labs ï½œ AI & Dev"
email:
description: Practical AI & Dev â€” tools, workflows, and real-world engineering
twitter_username: CryoZeroLabs
github_username: CryoZeroLabs
minimal_mistakes_skin: default
search: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
permalink: "/:categories/:title/"
# æ˜¾ç¤ºé¢åŒ…å±‘å¯¼èˆª
breadcrumbs: true
# åˆ†é¡µ
paginate: 5
paginate_path: "/page:num/"
timezone:
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
author:
  name: CryoZeroLabs
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Hi â€” Iâ€™m **CryoZero**, a software engineer. This is where I turn **AI** into durable productivityâ€”covering tools, workflows & automation, backend/devops, and data. I keep a simple standard: **Reusable. Verifiable. Shippable.** Expect playbooks, checklists, and real production notes. ğŸš€"
  links:
    - label: å¾®ä¿¡å…¬ä¼—å·ï¼šå†°é›¶çš„AIå·¥å…·åº“
      icon: fab fa-fw fa-weixin
      url: /
    - label: å°çº¢ä¹¦ã€æŠ–éŸ³åŒå…¬ä¼—å·
      icon: fab fa-fw fa-tiktok
      url: /
    - label: WeChatï¼šCryoZero
      icon: fab fa-fw fa-weixin
      url: /
footer:
  links:
    - label: å¾®ä¿¡å…¬ä¼—å·ï¼šå†°é›¶çš„AIå·¥å…·åº“
      icon: fab fa-fw fa-weixin
      url: https://mp.weixin.qq.com/s/6ezAjven7DIexwYnm3vNAA
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/CryoZeroLabs
    - label: CryoZeroLabs
      icon: fab fa-fw fa-twitter
      url: https://x.com/CryoZeroLabs
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      # æ˜¾ç¤ºæ—¥æœŸ
      show_date: true
      # æ˜¾ç¤ºé¢„è®¡é˜…è¯»æ—¶é—´
      read_time: true
      comments: true
      share: true
      related: true
      # è®¾ç½®æ–‡ç« å®½åº¦
      classes: wide
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
theme: minimal-mistakes-jekyll
# è°·æ­Œåˆ†æ
analytics:
  provider: "google-gtag" # GA4
  google:
    tracking_id: "G-2CWQ3VBQG6" # ä½ çš„ GA4 ID
    anonymize_ip: true
# å‹ç¼© HTML
compress_html:
  clippings: all
  ignore:
    envs: development # disable compression in dev environment
